services:
  gitlab:
    image: gitlab/gitlab-ee:latest
    container_name: gitlab
    restart: always
    hostname: gitlab.local
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8001'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        prometheus_monitoring['enable'] = true
        gitlab_rails['backup_keep_time'] = 604800  # バックアップ保持期間 (秒)
        nginx['listen_port'] = 80
        # 自動バックアップ設定
        gitlab_rails['backup_archive_permissions'] = 0644
        gitlab_rails['backup_pg_schema'] = 'public'
    ports:
      - "2222:22"
      - "8001:80"
      - "8443:443"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/users/sign_in"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 3m
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
      - e_backups:/backups
    networks:
      - gitlab-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "8002:9090"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - gitlab
    networks:
      - gitlab-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    user: "472"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    ports:
      - "8000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - prometheus
    networks:
      - gitlab-network

  webhook:
    image: python:3.9-slim
    container_name: gitlab-webhook
    restart: always
    working_dir: /app
    volumes:
      - ./webhook:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backup:/backup
    ports:
      - "9000:9000"
    command: ["sh", "-c", "pip install -r requirements.txt && python receiver.py"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - gitlab
    networks:
      - gitlab-network

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  e_backups:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/Users/shinlab/Desktop/gitlab-backup"

networks:
  gitlab-network:
    driver: bridge